language: perl
perl:
  #- "5.6.2"       # ancient
  #- "5.8"
  #- "5.8.4"
  #- "5.8.4-thr"
  #- "5.8.8"       # common, prebuilt version
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.18.1-thr"
  - "5.20"
  - "5.22"
  - "5.24"
  - "dev"
  - "blead"

matrix:
  allow_failures:
    - perl: blead
    - perl: 5.6.2

sudo: required

dist: trusty

before_install:
  - sudo apt-get -qq update
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - export SPLIT_BUILD=0
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - cpan-install ExtUtils::MakeMaker~6.68
  - cpan-install --deps

script:
  - cd $BUILD_DIR
  - perl Makefile.PL && make
  - prove -blv $(test-dirs)

branches:
  except:
    - /^wip\//
    - /^blocked/
